Repository likelion-ssu/introduction, pull requests merged in 2022-03, with the labels that each got.

#3 10th/daehwan2yo
  10th/daehwan2yo/README.md
Labels: 긴급, 도움

#35 feat(#18) : 임윤지 자기소개 추가
  10th/hoonjiv/README.md
Labels: 그냥

#34 feat(#8) : 하성원 자기소개 추가
  10th/swdevsw98/README.md
Labels: 긴급

#42 feat(#22): 유승민 자기소개 추가
  10th/99winnmin/README.md
Labels: 도움

#38 feat(#15) : 김윤미 자기소개 추가
  10th/youm0524/README.md
Labels: 테스트

#41 feat(#9) : 이준규 자기소개 추가
  10th/Jun99uu/Readme.md
Labels: 기능, 업그레이드

#31 10th/da-in
  10th/da-in/README.md
Labels: 그냥, 긴급

#39 feat(#7):이진형 자기소개 추가
  10th/INFINTIELION/README.md
Labels: duplicate

#52 feat(#49) : 서채연 자기소개 추가
  10th/seocylucky/README.md
Labels: 도움
